# -*- coding: utf-8 -*-
"""23_2 ESAA_project2_TextAnalysis_Korean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCAhlb0_ZDk94th8Bei5ZAET2Z9zrWK_

# ESAA OB 2조 프로젝트(2)

# 0. 대회 및 데이터 설명
## 0.1 대회 설명

[텍스트분석]

월간 데이콘 한국어 문장 관계 분류 AI 경진대회:
https://dacon.io/competitions/official/235875/overview/description

- 한 쌍의 문장은 Premise와 Hypothesis로 구성

    : premise 문장을 참고해 hypothesis 문장 판별
- hypothesis 문장 판별
  - Entailment (참인지)
  - Contradiction(거짓인지)
  - Neutral(참/거짓 여부를 알 수 없는 문장인지)
- goal: 한국어 문장 쌍 분석 모델 개발
- 심사 기준: Accuracy



## 0.2 데이터 설명
< **Natural Language Inference Dataset** >
- WIKITREE, policy, WIKINEWS, KIKIPDEIA, NSMC, AIRBNB: 현대 한국어의 다양한 주제와 문체를 다룸 (corpus, 말뭉치)
- WIKITREE, policy, WIKINEWS: 뉴스 기사
- WIKIPEDIA: 백과사전
- NSMC, AIRBNB: 각각 영화와 여행에 대한 구어체 리뷰. 일반적으로 공식적인 문장이 구어체 문장보다 어려움 -> 어려움을 조절하기 위해 구어체에서 더 많은 문장 추출


->  여섯 가지 corpus(말뭉치)에서 hypothesis를 유도할 수 있는 10,000개의 premise 추출

< **premise의 세 가지 조건** >

1. premise는 명제여야 함
  - 명제는 참 또는 거짓의 진리 값을 할당할 수 있는 진술문

2. premise에는 적어도 하나의 술어가 포함되어야 함
  - states(예: 있다, 믿다, 알다)
  - activities(예: 놀다, 웃다, 걷다)
  - achievements(예: 깨달다, 도달하다, 부수다)
  - accomplishments(예: 먹다, 짓다, 그리다)
  - 등의 다양한 술어

3. premise의 길이는 공백을 포함하여 20에서 90자여야 함

# 1. 패키지 및 데이터 불러오기

## 1.1 패키지 불러오기
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib
# %matplotlib inline

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

!apt-get update -qq
!apt-get install fonts-nanum* -qq

font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font_name = fm.FontProperties(fname=font_path, size=10).get_name()
print(font_name)
plt.rc('font', family=font_name)

matplotlib.rcParams['axes.unicode_minus'] = False

!pip install konlpy

from glob import glob
import os
import numpy as np
from tqdm import tqdm, tqdm_notebook

from konlpy.tag import Okt
from collections import Counter
from wordcloud import WordCloud

import warnings
warnings.filterwarnings('ignore')

"""## 1.2 데이터 불러오기"""

from google import colab
colab.drive.mount("/content/drive")

import pandas as pd
train = pd.read_csv("/content/drive/MyDrive/ESAA 23-2/project(2)/train_data.csv")
test = pd.read_csv("/content/drive/MyDrive/ESAA 23-2/project(2)//test_data.csv")
submission = pd.read_csv("/content/drive/MyDrive/ESAA 23-2/project(2)//sample_submission.csv")

# train 데이터 상단 부분 확인
train.head()

# train 데이터 구조 파악
print(train.shape)
print(test.shape)
print(submission.shape)

train.info()

test.info()

"""# 2. 데이터 시각화

## 2.1 Train Target 분포 확인
"""

# 히스토그램을 사용해서 데이터의 분포를 살펴보기
feature = train['label']

plt.figure(figsize=(10,7.5)) # 그래프 이미지 크기 설정

plt.title('label', fontsize=20)
temp = feature.value_counts() # feature 변수의 변수별 개수 계산
plt.bar(temp.keys(), temp.values, width=0.5)
plt.xticks(temp.keys(), fontsize=15)
plt.show()

"""> label이 일정하게 분포해 있다.

## 2.2 실제 Text와 가설 Text의 평균 길이
"""

premise_len_mean = np.mean(train['premise'].str.len()) # 리뷰 길이의 평균값 계산
print('실제 Text 평균 길이 :',premise_len_mean)

hypo_len_mean = np.mean(train['hypothesis'].str.len()) # 리뷰 길이의 평균값 계산
print('가설 Text 평균 길이 :',hypo_len_mean)

"""> 실제 Text의 평균 길이가 가설 Text의 평균 길이보다 길다.

### 1) 실제 Text 확인
"""

# 데이터 필터링을 위한 마스크 설정 (premise 부분만)
mask_true = (train.label == 'entailment')
mask_false = (train.label == 'contradiction')
mask_neutral = (train.label == 'neutral')

df_train = train.premise.copy()

df_true = train.loc[mask_true,:].premise
df_false = train.loc[mask_false,:].premise
df_neu = train.loc[mask_neutral,:].premise

# 세 집합을 리스트로 묶어줍니다.
compare = [df_train, df_true, df_false, df_neu]

df_true.head()

df_false.head()

df_neu.head()

# 히스토그램을 사용해서 데이터의 분포를 살펴봅니다.
plt.figure(figsize=(20,12))
plt.suptitle("Histogram: premise length", fontsize=40)
name = ['total dataset', 'entailment text', 'contradiction text', 'neutral text']

for i in range(len(compare)):
    document = compare[i]
    string_len = [len(x) for x in document]
    # print(string_len)
    plt.subplot(2, 2, i+1)
    plt.title(name[i], fontsize=20)
    plt.hist(string_len, alpha=0.5, color='orange')

plt.show()

""">- premise text의 경우 대부분 20~30자 사이에 분포해있고 최대 90자 정도까지 일정한 수치만큼 분포해 있다.
- 실제 text인 premise는 label 값에 관계없이 동일 히스토그램을 보여주고 있다.

### 2) 가설 text 확인
"""

# 데이터 필터링을 위한 마스크 설정 (Hypothesis 부분만)
mask_true = (train.label == 'entailment')
mask_false = (train.label == 'contradiction')
mask_neutral = (train.label == 'neutral')

df_train = train.hypothesis .copy()

df_true = train.loc[mask_true,:].hypothesis
df_false = train.loc[mask_false,:].hypothesis
df_neu = train.loc[mask_neutral,:].hypothesis

# 세 집합을 리스트로 묶어줍니다.
compare = [df_train, df_true, df_false, df_neu]

df_true.head()

df_false.head()

df_neu.head()

# 히스토그램을 사용해서 데이터의 분포를 살펴봅니다.
plt.figure(figsize=(20,12))
plt.suptitle("Histogram: hypothesis length", fontsize=40)
name = ['total dataset', 'entailment text', 'contradiction text', 'neutral text']

for i in range(len(compare)):
    document = compare[i]
    string_len = [len(x) for x in document]
    plt.subplot(2, 2, i+1)
    plt.title(name[i], fontsize=20)
    plt.hist(string_len, alpha=0.5, color='orange')

plt.show()

""">- 가설 text는 label 값에 따라 어느 정도 차이를 보여주지만 역시 20자 정도에 많이 분포해 있는 모습이다.

- 알 수 없는 문장은 참, 거짓에 비해 상대적으로 적은 양을 가지고도 가설 문장의 참/거짓/알수없다를 판별해내야 한다.

## 2.3 Word Cloud
"""

def df2str(df):
    # 전체 리뷰들을 하나의 문자열로 만듦
    s = [s for s in df]
    document = ""
    for i in range(len(s)):
        document += s[i]
    return document

def get_noun(text):
    # okt tagger를 이용해 명사 추출
    okt = Okt()
    noun = okt.nouns(text)
    for i,v in enumerate(noun):
        if len(v)<2:
            noun.pop(i)
    count = Counter(noun)
    noun_list = count.most_common(100)

    return noun_list

def visualize(noun_list, title):
    # 워드클라우드 이미지 생성
    wc= WordCloud(
        background_color='white', # 배경 색깔 정하기
        colormap = 'Dark2', # 폰트 색깔 정하기
        font_path = font_path,
        width = 800,
        height = 800).generate_from_frequencies(dict(noun_list))

    plt.figure(figsize=(10,10)) # 이미지 사이즈 지정
    plt.title(title, fontsize=20)
    plt.imshow(wc, interpolation='lanczos') # 이미지의 부드럽기 정도
    plt.axis('off') # x y 축 숫자 제거
    plt.show()  # 워드클라우드 이미지 확인

    return wc

document = df2str(df_train) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

"""### 1) Total_text"""

total_text = visualize(noun_list,'total text') # 워드클라우드 시각화

""">- 가설 문장의 참/거짓을 확인하기 어렵다.
- 영화가 크게 있는 걸 보면 영화 기사나 리뷰 글에서 나온 문장들도 있는 건가 궁금하다.
> > 전체적으로 Word Cloud 실행

### 2) Entailment
- Premise text를 label에 따라 Word Cloud
"""

# Entailment
document = df2str(df_true) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

true_text = visualize(noun_list,'true text') # 워드클라우드 시각화

""">- 라벨 구분 없이 Word Cloud를 진행했을 때랑 비슷한 형태가 나온다.
- 숙소, 사업, 위치, 호스트, 영화 이런 단어들은 제외해도 될 것 같다.

### 3) Contradiction
"""

# Contradiction
document = df2str(df_false) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

false_text = visualize(noun_list,'False text') # 워드클라우드 시각화

"""> 가설이 참인 문장을 워드클라우드 했을 때와 비슷한 형태인 것으로 보여진다.

### 4) Neutral
"""

# Neutral
document = df2str(df_neu) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

neutral_text = visualize(noun_list,'Neutral text') # 워드클라우드 시각화

"""### 5) Hypothesis text를 label에 따라 Word Cloud

#### (1) Entailment
"""

df_hy_train = train.hypothesis.copy()

df_hy_true = train.loc[mask_true,:].hypothesis
df_hy_false = train.loc[mask_false,:].hypothesis
df_hy_neu = train.loc[mask_neutral,:].hypothesis

document = df2str(df_hy_true) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

"""#### (2) Contradiction"""

document = df2str(df_hy_false) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

false_text = visualize(noun_list,'Hypothesis False text') # 워드클라우드 시각화

"""#### (3) Neutral"""

document = df2str(df_hy_neu) # 전체 리뷰들을 하나의 문자열로 만듦
noun_list = get_noun(document) # 명사 추출, 개수 셈
noun_list[:10]

neutral_text = visualize(noun_list,'Hypothesis Neutral text') # 워드클라우드 시각화

"""# 3. 전처리

## 3.1 라이브러리, 패키지 불러오기
"""

!pip install datasets transformers[sentencepiece]
!pip install accelerate
# To run the training on TPU, you will need to uncomment the followin line:
!pip install cloud-tpu-client==0.10 torch==1.9.0 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl
!pip install transformers

#TPU 사용을 위한 accelerate
from accelerate import Accelerator

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import random
from tqdm import tqdm
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold
from transformers import TrainingArguments, Trainer
from transformers import AutoModel,AutoModelForSequenceClassification, AutoConfig, AutoTokenizer
import gc
from transformers import AdamW
from transformers import get_scheduler, get_cosine_with_hard_restarts_schedule_with_warmup
from tqdm.auto import tqdm
from datasets import load_metric
import warnings
warnings.filterwarnings('ignore')
from accelerate import notebook_launcher

"""## 3.2 데이터셋 만들기 ( 데이콘+카카오+KLUE :추가로 2가지 데이터 다운 받아옴)




```
train = pd.read_csv('/content/drive/MyDrive/train_data.csv', encoding='utf-8')

test = pd.read_csv('/content/drive/MyDrive/test_data.csv', encoding='utf-8')

만약 추가적인 데이터 안불러올 때의 코드.
```


"""

# 카카오 데이터셋
kakao_snli = pd.read_csv('/content/drive/MyDrive/ESAA 23-2/project(2)/ESAA_한국어_논문/snli_1.0_train.ko.tsv', sep='\t', encoding='utf-8')
kakao_snli = kakao_snli[:100000]
kakao_dev = pd.read_csv('/content/drive/MyDrive/ESAA 23-2/project(2)//ESAA_한국어_논문/kakao/xnli.dev.ko.tsv', sep='\t', encoding='utf-8')
kakao_test = pd.read_csv('/content/drive/MyDrive/ESAA 23-2/project(2)//ESAA_한국어_논문/kakao/xnli.test.ko.tsv', sep='\t', encoding='utf-8')
kakao_dev = pd.concat([kakao_dev,kakao_test, kakao_snli])
kakao_dev.rename(columns = {'sentence1':'premise','sentence2':'hypothesis','gold_label':'label'},inplace=True)

# KLUE 데이터셋
klue_dev = pd.read_json('/content/drive/MyDrive/ESAA 23-2/project(2)//ESAA_한국어_논문/klue-nli-v1.1/klue-nli-v1.1_dev.json')
klue_dev = klue_dev[['premise', 'hypothesis', 'gold_label']]
klue_dev.rename(columns = {'gold_label':'label'}, inplace=True)

# 데이콘, 카카오, KLUE 데이터셋 병합
train = pd.concat([train, klue_dev, kakao_dev], axis=0)
train = train.reset_index(drop=True)
train['index'] = train.index
train = train.dropna()
train = train.reset_index(drop=True)
train['index'] = train.index
train

"""> 데이터는 동일한 premise에 세 가지의 hypothesis로 구성. 각각의 hypothesis는 대체로 contradiction, entailment, neutral이 하나씩 매칭"""

# 데이터셋이 잘 만들어졌는지 train, test data 확인
print(train.info(), end='\n\n')
print(test.info())

print('Train Columns: ', train.columns)
print('Test Columns: ', test.columns)

print('Train Label: ', train['label'].value_counts(), sep='\n', end='\n\n')
print('Test Label: ', test['label'].value_counts(), sep='\n')

print('Train Null: ', train.isnull().sum(), sep='\n', end='\n\n')
print('Test Null: ', test.isnull().sum(), sep='\n')

"""> null 값 없음"""

for i, sent in enumerate(train['premise'].unique()):
  if len(train[train['premise'] == sent]) == 3:
    continue
  else :
    print('value',sent)
    print(i)

"""> 세 가지의 hypothesis를 가지지 않은 premise -> 삭제? 남겨둠?"""

num_contradiction = len(train[train['label'] == 'contradiction'])
num_entailment = len(train[train['label'] == 'entailment'])
num_neutral = len(train[train['label'] == 'neutral'])

labels = ['contradiction', 'entailment', 'neutral']
counts = [num_contradiction, num_entailment, num_neutral]

plt.bar(labels, counts)
plt.show

"""> train셋의 label은 contradiction, entailment, neutral이 고르게 분포

- label_num 칼럼 추가

  -> "entailment": 0, "contradiction": 1, "neutral": 2, "answer": 3 으로 지정
"""

def label_to_num(label):
    label_dict = {"entailment": 0, "contradiction": 1, "neutral": 2, "answer": 3}
    num_label = []

    for v in label:
        num_label.append(label_dict[v])

    return num_label

label_num = label_to_num(train['label'])
train['label_num']=label_num
train.head()

"""## 3.3 함수 생성"""

# "klue/roberta-large" 모델: KLUE (Korean Language Understanding Evaluation) 벤치마크를 위해 훈련된 RoBERTa 모델의 큰 버전

from transformers import AutoTokenizer

checkpoint = 'klue/roberta-large'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

token_map = tokenizer.special_tokens_map
token_map

premise = train['premise']
premise = premise.tolist()

hypothesis = train['hypothesis']
hypothesis = hypothesis.tolist()

# train['premise'] 리스트 각 요소 토큰화

for i in premise:
  tokened1_pre = tokenizer.tokenize(i)

# train['hypothesis'] 리스트 각 요소 토큰화

for i in hypothesis:
  tokened1_hyp = tokenizer.tokenize(i)

# BERT 모델의 훈련 또는 평가를 위해 데이터를 준비하는 데 사용

class BERTDataset(torch.utils.data.Dataset):
    def __init__(self, pair_dataset, label):
        self.pair_dataset = pair_dataset
        self.label = label

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() for key, val in self.pair_dataset.items()}
        item['labels'] = torch.tensor(self.label[idx])

        return item

    def __len__(self):
        return len(self.label)

#  주어진 레이블(문자열로 된 분류 레이블)을 해당하는 숫자 또는 인덱스로 변환하는 함수

def label_to_num(label):
    label_dict = {"entailment": 0, "contradiction": 1, "neutral": 2, "answer": 3}
    num_label = []

    for v in label:
        num_label.append(label_dict[v])

    return num_label

# 모델의 정확도(accuracy)를 계산

def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

train.head()

"""## 3.4 추가적인 한국어 토크나이징 라이브러리 (위에것과 다른 방법. 위에 방식 사용할 경우 필요 없음)

1. KoNLpy

기본적인 한국어 자연어 처리를 위한 파이썬 라이브러리

한국어는 토큰 단위를 형태소 단위로 사용할 때 단어와 품사의 정보를 같이 활용할 수 있기 때문에 효과적임

다른 형태소 분석기에 비해 속도가 느리지만 지원하는 품사 태그가 다양해서 속도가 느리더라도 정확한 품사 정보가 필요할 때 사용


- 형태소 분석기
    - 한국어의 복잡한 특성에 따라 문장에서 형태소를 분석할 수 있는 도구

    - 문장에서 형태소, 어근, 접두사/접미사, 품사 등 다양한 언어적 속성의 구조를 파악해줌

    - 형태소의 의미를 고려해 품사를 태깅
"""

pip install konlpy

from konlpy.tag import Okt  # 형태소 분석기로 Okt 사용
import re

def tokenize_korean_sentences(dataframe, column_name):
    okt = Okt()  # Okt 형태소 분석기 객체 생성

    tokenized_sentences = []
    for sentence in dataframe[column_name]:
        sentence = re.sub('[^가-힣a-z]', ' ', sentence) #간단한 전처리
        tokens = okt.morphs(sentence)  # 문장을 형태소 단위로 토큰화
        tokenized_sentences.append(tokens)

    return tokenized_sentences

tokens_hyp = tokenize_korean_sentences(train, 'hypothesis')

tokens_hyp

hyp_sentences = [' '.join(inner_list) for inner_list in tokens_hyp]

hyp_sentences

tokens_pre=tokenize_korean_sentences(train, 'premise')

tokens_pre

pre_sentences = [' '.join(inner_list) for inner_list in tokens_pre]

pre_sentences

"""- TF-IDF

: min_df=n로 설정하면 빈도수가 n 이상인 단어들만 TF-IDF 계산에 사용
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# hypothesis

tfidf_hyp = TfidfVectorizer(min_df=0)
tfidf_vectorizer_hyp = tfidf_hyp.fit_transform(hyp_sentences)

# 변환된 단어 목록 출력
tfidf_dict_hyp = tfidf_hyp.get_feature_names_out()
print(tfidf_dict_hyp)

# TF-IDF로 변환된 행렬을 출력
print(tfidf_vectorizer_hyp.toarray())

# premise


tfidf_pre = TfidfVectorizer(min_df=0)
tfidf_vectorizer_pre = tfidf_pre.fit_transform(pre_sentences)

# 변환된 단어 목록 출력
tfidf_dict_pre = tfidf_pre.get_feature_names_out()
print(tfidf_dict_pre)

# TF-IDF로 변환된 행렬을 출력
print(tfidf_vectorizer_pre.toarray())

"""# 4. 모델 학습
## 4.1 Roberta

"""

valid = train[20000:]
train = train[:20000]

!pip install transformers

from transformers import AutoTokenizer

model_name = "klue/roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

from tqdm import tqdm
import numpy as np

def convert_examples_to_features(sent_list1, sent_list2, max_seq_len, tokenizer):

    input_ids, attention_masks, token_type_ids = [], [], []

    for sent1, sent2 in tqdm(zip(sent_list1, sent_list2), total=len(sent_list1)):
        encoding_result = tokenizer.encode_plus(sent1, sent2,
                                                max_length=max_seq_len,
                                                pad_to_max_length=True)

        input_ids.append(encoding_result['input_ids'])
        attention_masks.append(encoding_result['attention_mask'])
        token_type_ids.append(encoding_result['token_type_ids'])

    input_ids = np.array(input_ids, dtype=int)
    attention_masks = np.array(attention_masks, dtype=int)
    token_type_ids = np.array(token_type_ids, dtype=int)

    return (input_ids, attention_masks, token_type_ids)

print("premise 최대 길이:", train['premise'].map(len).max())
print("hypothesis 최대 길이:", train['hypothesis'].map(len).max())

print("premise 최대 길이:", test['premise'].map(len).max())
print("hypothesis 최대 길이:", test['hypothesis'].map(len).max())

max_seq_len = 100
X_train = convert_examples_to_features(train['premise'], train['hypothesis'],
                                       max_seq_len=max_seq_len,
                                       tokenizer=tokenizer)

X_valid = convert_examples_to_features(valid['premise'], valid['hypothesis'],
                                       max_seq_len=max_seq_len,
                                       tokenizer=tokenizer)

X_test = convert_examples_to_features(test['premise'], test['hypothesis'],
                                       max_seq_len=max_seq_len,
                                       tokenizer=tokenizer)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(train['label'])
y_valid = le.transform(valid['label'])

label_idx = dict(zip(list(le.classes_), le.transform(list(le.classes_))))
label_idx

from tensorflow.keras import Model
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import TruncatedNormal
from transformers import TFAutoModel

from transformers import TFRobertaModel

class TFBertForSequenceClassification(Model):
    def __init__(self, model_name):
        super(TFBertForSequenceClassification, self).__init__()
        self.roberta = TFRobertaModel.from_pretrained(model_name, num_labels=3, from_pt=True)
        self.classifier = Dense(3, kernel_initializer=TruncatedNormal(0.02), activation='softmax')

    def call(self, inputs):
        input_ids, attention_mask, token_type_ids = inputs
        outputs = self.roberta(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        cls_token = outputs[1]
        prediction = self.classifier(cls_token)

        return prediction

# 사용 예시
model = TFRobertaForSequenceClassification("roberta-base")
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

import tensorflow as tf

model = TFBertForSequenceClassification(model_name)
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)

model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics='accuracy')

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_accuracy",
    min_delta=0.001,
    patience=2)

model.fit(
    X_train, y_train, epochs=2, batch_size=64, validation_data=(X_valid, y_valid),
    callbacks = [early_stopping]
)

pred = model.predict(X_test)

result = [np.argmax(val) for val in pred]

out = [list(label_idx.keys())[_] for _ in result]
out[:3]

submission["label"] = out

submission.to_csv("RoBerta.csv", index=False)